dist: xenial
language: java
addons:
  apt:
    packages:
      - ant
notifications:
  email:
    recipients: brash@jlab.org
    on_failure: always
before_install:
  - sudo apt-get install ant-optional
script: ant clean compile jar test Money HelloWorld HelloWorld2 AbstractClassExample AgeChecker ArrayListExample ArrayListPrintable CastingExample Conditional IncrementAge Loop MathExample MethodOne MethodOverload StringExample Switch
