dist: xenial
language: java
addons:
  apt:
    packages:
      - ant
script: ant compile jar HelloWorld HelloWorld2 AbstractClassExample AgeChecker ArrayListExample ArrayListPrintable CastingExample Conditional IncrementAge Loop MathExample MethodOne MethodOverload StringExample Switch
